merda = input('Digite algo: ')
print('------------------------------')
print(type(merda))
print('------------------------------')
print('alnum: ', merda.isalnum())
print('------------------------------')
print('numeric: ', merda.isnumeric())
print('------------------------------')
print('alpha: ', merda.isalpha())
print('------------------------------')
print('ascii: ', merda.isascii())
print('------------------------------')
print('decimal: ', merda.isdecimal())
print('------------------------------')
print('digit: ', merda.isdigit())
print('------------------------------')
print('upper: ', merda.isupper())
print('------------------------------')