print('===Desfio03===')
print('--------------------------------------------------------')
print('SOMADOR')
n1 = input('Informe um número inteiro: ')
n2 = input('Informe outro número interio ')
print(n1 + n2)
print('--------------------------------------------------------')
print('Encerrando...')
print('--------------------------------------------------------')
