print('                        ===Desafio02===')
print('---------------------------------------------------------------------')
print('Sua data de nascimento')
print('---------------------------------------------------------------------')
dia = input('Em qual dia você nasceu pequeno(a) garfanhoto(a)? ')
print('---------------------------------------------------------------------')
mes = input('Em qual mês você nasceu pequeno(a) garfanhoto(a)? ')
print('---------------------------------------------------------------------')
ano = input('Em qual ano você nasceu pequeno(a) garfanhoto(a)? ')
print('---------------------------------------------------------------------')
print('Você nasceu no dia ',dia, 'de ' ,mes, 'do ano de ' ,ano, '. Certo? ')
print('---------------------------------------------------------------------')

print('                         Encerrando...')
print('                               :)')
print('---------------------------------------------------------------------')

